### ISSUE TITLE
Float TTL does not work with memcached pylibmc

### ISSUE THREAD

**Issue by flaker** [mbr/simplekv#23]
Hi,

I was moving some project from a test scenario to use simplekv with memcache and pylibmc. SimpleKV tries to intercept bad ttl values by checking for [int, float] but in any case, the call to pylibmc `set`will result in an error if  float value is used.

Sample code follows:

```python
import pylibmc
from simplekv.memory import memcachestore

mc = pylibmc.Client(["127.0.0.1"], binary=True, behaviors={"tcp_nodelay": True, "ketama": True})
store = memcachestore.MemcacheStore(mc)
store.put("the_key", "the_data", ttl_secs=3.4)
```

The result is:

```
Traceback (most recent call last):
  File "prueba.py", line 6, in <module>
    store.put("the_key", "the_data", ttl_secs=3.4)
  File "/Users/fdelgado/dev/Bouncer/venv/lib/python2.7/site-packages/simplekv/__init__.py", line 374, in put
    return self._put(key, data, self._valid_ttl(ttl_secs))
  File "/Users/fdelgado/dev/Bouncer/venv/lib/python2.7/site-packages/simplekv/memory/memcachestore.py", line 53, in _put
    if not self.mc.set(key.encode('ascii'), data, time=time):
TypeError: integer argument expected, got float
```

The libs used are:
 * simplekv==0.9.2
 * pylibmc==1.4.1

against memcache 1.4.14.

I understand that memcache ttl is an unix timestamp. That should be whole seconds, right?

Thanks for any help.

Federico

**Comment by mbr** [comment]
A unix timestamp is usually an integer, but sometimes it is not (Python, for example, uses float timestamps). I've checked the memcached protocol and in my understanding memcached expects an integer.

Since for that reason it is impossible to have great-than-second accuracy for these things anyway, I've added a cast-to-int. If the tests pass (which I hope they do), could you check if 3709f90c6ef1d2421a11d4ac8b631a587f349814 fixes things for you?

**Comment by flaker** [comment]
Your commit is exactly the change I introduced and is working fine for me.
Thanks for the fast response.

Federico
